### ISSUE TITLE
Prompts of Tiktok dance video

### ISSUE THREAD

**Issue by fhlt** [chavinlo/TempoFunk#1]
Hi，I wonder what prompts for TikTok videos you used?

**Comment by chavinlo** [comment]
"Dancing, Choreography"
Although it only works if you heavily overfit:
input image:
![dancer](https://user-images.githubusercontent.com/85657083/223196101-d43e0895-8ed7-471e-bcc1-36575fffd0db.png)
output:
![ezgif com-optimize (1)](https://user-images.githubusercontent.com/85657083/223196503-8a23b1a4-9681-4bcf-ab42-7861b0ca25c4.gif)

If you don't want to overfit, you are gonna have to use another dataset with better labels. We used webvid and it worked much better, finally being able to use the initial frame.
output (same input as above):
![ezgif com-resize (1)](https://user-images.githubusercontent.com/85657083/223196939-b04a29f0-7779-4174-bfe6-6b2e020abfa2.gif)
